### PR TITLE
scholar's-saga_2_2_home-page-creation

### LINKED ISSUE #2: <Home Page>Page Creation
As a developer, I want to create a landing page to serve as the starting point of the app to route to all the other pages as a centralized hub.

Acceptance Criteria:

1. URL routes to home page first.
2. User Log-in link prominently displayed.
3. Generic calendar school academic events.
4. Generic student educational registration to-dos.

Checklist:

- [ ] Recall DB info when student logs in, rendering account info on page, and populating components below.
- [ ] Establish calendar component for displaying events and deadlines (generalized when not logged in, personalized once logged in)
- [ ] Establish To-Do component (generalized when not logged in, personalized once logged in)
- [x] Establish Profile card component (Profile picture, Profile link/button, Profile settings, Logout/Sign Out)
- [ ] Create generalized news feed relating to Scholar's Saga developments

### PR DESCRIPTION
**Pull request by nwm516**
UAT Rundown link: https://www.loom.com/share/da528c9f3c614f829dd7f715aa11f508?sid=9dcbea70-9a0b-4733-8465-8857c1b44d66

Resolves #2 

This is the current placeholder for the home page. It includes links for future pages, profile card with links to future pages also, and placeholder spots for components that will be later incorporated. 

Home Page - Sprint 2

### CODE REVIEW

**Review by JoyZhang2023 — COMMENTED** [review]
Seems ProfileCard component is missing.
image

**Comment by nwm516** [comment]
> Seems ProfileCard component is missing. image

Forgotten ProfileCard component has been added!

**Review by JoyZhang2023 — APPROVED** [review]
LGTM. Home page display as described.
image

**Review by mx-cifu — APPROVED** [review]
Everything looks good! I managed to switch to your branch and all the files looked good, and was able to run everything to the point shown in the demo.

**Pull request merged**
